// Recap Cloudflare Worker — proxies cloud-summary requests to Gemini 3.1 Flash Lite.
//
// The app never holds the Gemini API key. Per-install tokens are validated
// here; abuse → rate-limit → reject.
//
// Deploy: `wrangler deploy`. Set secrets:
//   wrangler secret put GEMINI_API_KEY
//   wrangler secret put INSTALL_TOKEN_PEPPER

export interface Env {
  GEMINI_API_KEY: string;
  INSTALL_TOKEN_PEPPER: string;
  RATE_LIMIT: KVNamespace;
}

interface SummarizeRequest {
  persona_key: string;
  prompt: string;
  transcript: string;
}

interface SummarizeResponse {
  text: string;
  model_id: string;
}

const GEMINI_ENDPOINT =
  'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent';

// Per-install: 60 cloud summaries per hour. App-side quota is the source of
// truth; this is just abuse mitigation.
const RATE_LIMIT_PER_HOUR = 60;

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (request.method === 'POST' && url.pathname === '/v1/summarize') {
      return handleSummarize(request, env);
    }
    return new Response('Not found', { status: 404 });
  },
};

async function handleSummarize(request: Request, env: Env): Promise<Response> {
  // 1. Auth — Bearer <install_token>.
  const auth = request.headers.get('Authorization') ?? '';
  if (!auth.startsWith('Bearer ')) {
    return json({ error: 'missing bearer token' }, 401);
  }
  const installToken = auth.slice('Bearer '.length).trim();
  if (!isValidInstallToken(installToken, env.INSTALL_TOKEN_PEPPER)) {
    return json({ error: 'invalid install token' }, 401);
  }

  // 2. Rate limit (per-install, hourly).
  const hour = new Date().toISOString().slice(0, 13); // YYYY-MM-DDTHH
  const rateKey = `rl:${installToken}:${hour}`;
  const used = parseInt((await env.RATE_LIMIT.get(rateKey)) ?? '0', 10);
  if (used >= RATE_LIMIT_PER_HOUR) {
    return json({ error: 'rate limited' }, 429);
  }
  await env.RATE_LIMIT.put(rateKey, String(used + 1), { expirationTtl: 3700 });

  // 3. Body.
  let body: SummarizeRequest;
  try {
    body = (await request.json()) as SummarizeRequest;
  } catch {
    return json({ error: 'invalid json body' }, 400);
  }
  if (!body.transcript || !body.prompt) {
    return json({ error: 'transcript + prompt required' }, 400);
  }

  // 4. Call Gemini Flash Lite.
  const geminiBody = {
    contents: [
      {
        parts: [
          {
            text: `${body.prompt.trim()}\n\nTranscript:\n${body.transcript}`,
          },
        ],
      },
    ],
    generationConfig: {
      temperature: 0.4,
      topK: 40,
      maxOutputTokens: 2048,
    },
  };

  const geminiResp = await fetch(
    `${GEMINI_ENDPOINT}?key=${env.GEMINI_API_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(geminiBody),
    },
  );

  if (!geminiResp.ok) {
    const errText = await geminiResp.text();
    return json(
      { error: `gemini ${geminiResp.status}`, detail: errText.slice(0, 500) },
      502,
    );
  }

  const geminiJson = (await geminiResp.json()) as any;
  const text: string | undefined =
    geminiJson?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    return json({ error: 'gemini returned no text' }, 502);
  }

  const out: SummarizeResponse = {
    text: text.trim(),
    model_id: 'gemini-3.1-flash-lite',
  };
  return json(out, 200);
}

function json(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}

/**
 * Validate per-install token: app sends HMAC-SHA256(install_uuid, PEPPER).
 * We don't store install UUIDs — we just verify the token shape and that
 * it could plausibly have been generated by our pepper.
 *
 * For v1 we accept any 64-hex-char string with the right length. Server-side
 * we rate-limit by token. Upgrade to actual HMAC verification once we
 * generate per-install tokens during sign-in (Free+ tier).
 */
function isValidInstallToken(token: string, _pepper: string): boolean {
  return /^[a-fA-F0-9]{64}$/.test(token);
}
